name: Consumer Contract Test & Publish
on:
  push:
    branches: [main]
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pact-consumer-example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Debug npm config
        run: |
          npm config list
          echo "npm prefix: $(npm prefix)"
          echo "npm version: $(npm -v)"
          echo "node version: $(node -v)"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Pact CLI explicitly
        run: npm install @pact-foundation/pact-cli
      
      - name: Run consumer pact tests
        run: npm test
      
      - name: Check directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents of node_modules/.bin:"
          ls -la node_modules/.bin || echo "node_modules/.bin directory does not exist"
          echo "Contents of pacts directory (if exists):"
          ls -la pacts || echo "pacts directory does not exist"
          echo "Package.json contents:"
          cat package.json
      
      - name: Try direct path to pact-cli
        run: |
          ./node_modules/.bin/pact-broker publish pacts \
            --consumer-app-version $GITHUB_SHA \
            --broker-base-url ${{ secrets.PACT_BROKER_BASE_URL }} \
            --broker-token ${{ secrets.PACT_BROKER_TOKEN }}
        continue-on-error: true
      
      - name: Alternative publish approach
        run: |
          npm run "pact:publish" -- \
            --consumer-app-version $GITHUB_SHA \
            --broker-base-url ${{ secrets.PACT_BROKER_BASE_URL }} \
            --broker-token ${{ secrets.PACT_BROKER_TOKEN }}
        continue-on-error: true
