name: Provider Verification

on:
  push:
    branches: [main]

jobs:
  verify-contract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: pact-provider-example
        run: npm ci

      - name: Start provider
        working-directory: pact-provider-example
        run: |
          nohup node provider.js &
          sleep 5

      - name: Verify pact from broker
        working-directory: pact-consumer-example
        run: |
          npx pact verify \
            --provider-base-url http://localhost:8081 \
            --broker-url ${{ secrets.PACT_BROKER_BASE_URL }} \
            --broker-token ${{ secrets.PACT_BROKER_TOKEN }} \
            --provider-version $GITHUB_SHA \
            --provider UserService \
            --publish-verification-results \
            --enable-pending

