name: Provider Verification
on:
  push:
    branches: [main]
jobs:
  verify-contract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        working-directory: pact-provider-example
        run: npm ci
      
      - name: Install Pact CLI explicitly
        working-directory: pact-provider-example
        run: npm install @pact-foundation/pact-cli
      
      - name: Diagnostic Step - Check available commands
        working-directory: pact-provider-example
        run: |
          echo "Available commands in pact-broker:"
          ./node_modules/.bin/pact-broker help || echo "No help command available"
          echo "Checking for verify-provider command:"
          ./node_modules/.bin/pact-broker verify-provider --help || echo "verify-provider command not available"
          echo "Installing pact-node:"
          npm install @pact-foundation/pact-node
          echo "Checking for pact-verifier binary:"
          ls -la ./node_modules/.bin/pact-*
      
      - name: Start provider
        working-directory: pact-provider-example
        run: |
          nohup node provider.js &
          sleep 5
      
      - name: Verify pact from broker - Attempt 1
        working-directory: pact-provider-example
        run: |
          # Try with pact-verifier if available
          if [ -f "./node_modules/.bin/pact-verifier" ]; then
            ./node_modules/.bin/pact-verifier \
              --provider-base-url http://localhost:8081 \
              --broker-url ${{ secrets.PACT_BROKER_BASE_URL }} \
              --broker-token ${{ secrets.PACT_BROKER_TOKEN }} \
              --provider-version $GITHUB_SHA \
              --provider UserService \
              --publish-verification-results \
              --enable-pending
          else
            echo "pact-verifier not found"
          fi
        continue-on-error: true
      
      - name: Verify pact from broker - Attempt 2
        working-directory: pact-provider-example
        run: |
          # Install pact-provider-verifier separately
          npm install pact-provider-verifier
          # Try with pact-provider-verifier if available
          if [ -f "./node_modules/.bin/pact-provider-verifier" ]; then
            ./node_modules/.bin/pact-provider-verifier \
              --provider-base-url http://localhost:8081 \
              --pact-broker-base-url ${{ secrets.PACT_BROKER_BASE_URL }} \
              --pact-broker-token ${{ secrets.PACT_BROKER_TOKEN }} \
              --provider-version $GITHUB_SHA \
              --provider-name UserService \
              --publish-verification-results \
              --enable-pending
          else
            echo "pact-provider-verifier not found"
          fi
